// Writes the issue reference from the table in packages/core/src/issues.ts: one page per code under
// packages/cli/docs/errors/, which ships in the kalup package, and the website's errors reference. Both are committed.
// Run it from anywhere after editing the table:
//
//   pnpm gen                 (node --experimental-strip-types scripts/gen-docs.mjs)
//   pnpm gen --check         writes nothing; exits 1 when a generated file is missing, stale or left over
//
// The CLI tests run --check, so a table edit without `pnpm gen` fails them.
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { issues } from '../packages/core/src/issues.ts'

const root = fileURLToPath(new URL('..', import.meta.url))
const pages = join(root, 'packages/cli/docs/errors')
const website = join(root, 'apps/web/content/docs/reference/errors.mdx')

const intro = `---
title: Errors and warnings
description: Every E_ and W_ code Kalup can print, what it means, its exit code and how to fix it
---

{/* Generated by scripts/gen-docs.mjs from packages/core/src/issues.ts. Edit the table there, then run pnpm gen. */}

Every problem Kalup reports is an issue with a code. \`E_\` codes are errors: the command stopped or found something invalid. \`W_\` codes are warnings: the command finished and the exit code stays 0, except that \`pull --check --exit-code\` exits 2 on a difference a warning reports ([W_CODEC_MISMATCH](#w_codec_mismatch), or [W_UNSUPPORTED_TYPE](#w_unsupported_type) for a property in the file), \`compare\` exits 1 with \`E_INCOMPLETE\` when [W_UNADDRESSABLE_NAME](#w_unaddressable_name) leaves out a property config names, and an \`apply\` run with [W_UNVERIFIED](#w_unverified) exits 5 because not every effect verified.

Each code has its own section on this page, with a stable anchor you can link to: \`/docs/reference/errors#e_not_data\`. An issue in the output also names the matching page in the installed package, for example \`(docs: errors/E_NOT_DATA.md)\`. It is the same content.

In \`--json\` mode every issue has \`code\`, \`message\`, and often \`file\`, \`line\`, \`configPath\`, \`fix\` and \`humanRequired\`. [JSON output](/docs/reference/json-output) describes the fields, and [Exit codes](/docs/reference/exit-codes) the numbers.

<Callout type="info">
Agents: act on \`fix\`, not on the message. On exit 3, fix the file and line the issue names, then validate again. On exit 4 or \`humanRequired: true\`, stop and hand the issue to the user.
</Callout>`

const warningsIntro =
  "A warning leaves the exit code alone, except under `pull --check --exit-code`, where `W_CODEC_MISMATCH` and a `W_UNSUPPORTED_TYPE` for a property in the file count as differences (exit 2). In human output it is printed on stderr after the command's output; with `--json` it is in `issues` next to `ok: true`."

function fence(lang, lines) {
  return `\`\`\`${lang}\n${lines.join('\n')}\n\`\`\``
}

function example(issue, outputLang) {
  if (!issue.example) {
    return []
  }
  const { config, output } = issue.example
  return [...(config ? [fence('ts', config)] : []), fence(outputLang, output)]
}

function page(code, issue) {
  const parts = [`# ${code}`, issue.summary, '## When', ...issue.when, '## Fix', ...issue.fix]
  if (issue.example) {
    parts.push('## Example', ...example(issue, ''))
  }
  return `${parts.join('\n\n')}\n`
}

// The package pages link to their sibling pages; the website has its own page, and title, for the same content.
const webLinks = {
  '../config.md#builders': ['Property builders', '/docs/config/property-builders#the-builders'],
  '../config.md#the-grammar': ['Config files', '/docs/config/config-files#the-grammar'],
  '../state.md#target-rebind': ['target rebind', '/docs/commands/state#target-rebind'],
  '../targets.md#choosing-a-target': ['Targets and credentials', '/docs/concepts/targets-and-credentials'],
}

// Website prose: another code in backticks links to its section, and a package page link to its website page.
function web(code, text) {
  const linked = text.replace(/`([EW]_[A-Z_]+)`/g, (match, other) =>
    other !== code && Object.hasOwn(issues, other) ? `[${match}](#${other.toLowerCase()})` : match,
  )
  return linked.replace(/\[[^\]]*\]\((\.\.\/[^)]+)\)/g, (_, target) => {
    if (!Object.hasOwn(webLinks, target)) {
      throw new Error(`${code} links to ${target}, which has no website page in webLinks`)
    }
    const [title, url] = webLinks[target]
    return `[${title}](${url})`
  })
}

function section(code, issue) {
  const [fix, ...more] = issue.fix
  const prose = [issue.summary, ...issue.when, `**Fix.** ${fix}`, ...more].map((text) => web(code, text))
  return [`### ${code}`, ...prose, ...example(issue, 'text')].join('\n\n')
}

function reference() {
  const entries = Object.entries(issues)
  const rows = entries.map(([code, issue]) => `| [${code}](#${code.toLowerCase()}) | ${issue.exit} | ${issue.title} |`)
  const errors = entries.filter(([code]) => code.startsWith('E_')).map(([code, issue]) => section(code, issue))
  const warnings = entries.filter(([code]) => code.startsWith('W_')).map(([code, issue]) => section(code, issue))
  return `${[
    intro,
    '## Index',
    ['| Code | Exit | Meaning |', '| --- | --- | --- |', ...rows].join('\n'),
    '## Errors',
    ...errors,
    '## Warnings',
    warningsIntro,
    ...warnings,
  ].join('\n\n')}\n`
}

const expected = new Map([
  ...Object.entries(issues).map(([code, issue]) => [join(pages, `${code}.md`), page(code, issue)]),
  [website, reference()],
])
const leftOver = readdirSync(pages)
  .map((name) => join(pages, name))
  .filter((file) => !expected.has(file))
const stale = [...expected].filter(([file, text]) => !existsSync(file) || readFileSync(file, 'utf8') !== text)

if (process.argv.includes('--check')) {
  const problems = [...stale.map(([file]) => file), ...leftOver].map((file) => relative(root, file))
  if (problems.length > 0) {
    process.stderr.write(`Out of date, run pnpm gen:\n${problems.map((file) => `  ${file}\n`).join('')}`)
    process.exit(1)
  }
} else {
  for (const [file, text] of stale) {
    writeFileSync(file, text)
  }
  for (const file of leftOver) {
    rmSync(file)
  }
  process.stdout.write(`${stale.length} written, ${leftOver.length} removed\n`)
}
